### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by elmanevala** [veelupu/ot-harjoitustyo#1]
## Koodikatselmointi

* Koodi haettu 26.4.2020 klo 18.00.

Sovelluksen koodi oli selkeää ja varisnkin suuret kokonaisuudet oli toteutettu hyvin. Koko sovelluksen rakenne oli eriytetty, niin että käyttöliittymä, logiikka ja tiedon tallennus olivat erikseen. Yleisesti ottaen minun oli helppo ymmärtää sovelluksen toimintalogiikka dokumentoinnin avulla.

Sovelluksesta puuttui vielä muutamia vaatimusmäärittelyn osia. Puuttuvatkin osat oli jo hahmoteltu koodiin ja myös se auttoi ymmärtämään koodia.

Vaikka pakkaukset olivat selkeitä, ne oli nimetty suositusten vastaisesti camelCase-tyylillä, mutta luokkien koodissa pakkaus oli lowercasetyylinen. Tästä myös NetBeans varoitti ja sen voi helposti korjata refraktoroimalla.

DBHikeDao-luokan metodi createCompanion oli melko pitkä. Se kostuu selkeästi kahdesta eri osasta. Molemmista osista voisi tehdä omat metodinsa.

Koodissa oli myös muutamia bugeja.

Jos käyttäjä syöttää integerien sijaan tekstiä repun painon kohdille, tulee sovellukseen virheviesti, jossa sanotaan, että tekstiä on vuosi-TextFieldissä. Virheviesti voisi eritellä virheet myös repun painon kohdalla tai ilmoittaa yleisesti "jossain on tekstiä".

Sovellus tulostaa StackTracen komentoriville, jos yrittää lisätä tyhjää vaellusta tai lisätä saman nimistä vaellusta uudestaan. StackTracen ei pitäisi tulostua missään tilanteessa.
StackTrace tulostuu myös, jos käyttäjä vahingossa lisää saman kaverin kaksi kertaa vaellukselle.

Kokonaisuutena sovelluksen koodia oli helppo ymmärtää ja muutamista bugeista huolimatta, sovellus toimi hyvin.

Tykkäsin myös sovelluksen ideasta! Ehkä käytän valmista sovellusta seuraavallla vaelluksellani.

**Comment by veelupu** [comment]
Kiitos paljon kommenteista ja erityisesti hyvistä huomioista! Niistä oli paljon apua harjoitustyön kehittämisessä. Mukavaa, jos tästä olisi iloa tulevilla vaelluksilla.
